/* absolute_value()
 * ----------------
 * Function returns the absolute value of its argument (x).
 *
 * REF: This function was generated by ChatGPT.
 * REF: The function name was then modified to comply with the style guide.
 */
int absolute_value(int x) {
    if (x < 0) {
        return -x;
    } else {
        return x;
    }
}

