/* abs()
 * -----
 * Function returns the absolute value of a number (n).
 *
 * REF: This function and most of the description above was generated by 
 * REF: Github CoPilot. The indentation was then modified to comply with 
 * REF: the style guide.
 */
int abs(int n) {
    if (n < 0) {
        return -n;
    }
    return n;
}

